### ISSUE TITLE
Black error on Ubuntu 18.04.03

### ISSUE THREAD

**Issue by Solemnly** [turicas/crau#12]
Fresh installed and updated system:

Could not find a version that satisfies the requirement black (from -r requirements-development.txt (line 3)) (from versions: )
No matching distribution found for black (from -r requirements-development.txt (line 3))

tryd it with normal pip, results in an setup egg error. Dunno why it not updated the outdated stuff.
If someone has this also this error: 

> pip install --upgrade setuptools

And then run 

> pip install crau

 again.

**Comment by turicas** [comment]
Which Python version? `crau` is tested under python3.7+.

**Comment by Solemnly** [comment]
> 
> 
> Which Python version? `crau` is tested under python**3.7**+.

I think thats the point. So, this can be closed for now.

**Comment by turicas** [comment]
Try:
```bash
apt update
apt install --reinstall python3-apt python3-pip
pip3 install -U crau
```

**Comment by shuaishuai1999** [comment]
i also met the problem,follow your tips,but it's not work.
